"""role

Revision ID: 08707e7dcc99
Revises: 367ad28b91a7
Create Date: 2022-05-27 14:07:27.423106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08707e7dcc99'
down_revision = '367ad28b91a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_professor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_professor')
    op.drop_column('user', 'is_student')
    # ### end Alembic commands ###
