"""subjects

Revision ID: 1dfc6c534742
Revises: 23835d505398
Create Date: 2022-05-08 23:08:25.080680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfc6c534742'
down_revision = '23835d505398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
