"""subjects

Revision ID: 23835d505398
Revises: 420c0a9dde40
Create Date: 2022-05-08 23:07:30.768484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23835d505398'
down_revision = '420c0a9dde40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
