"""subjects

Revision ID: 284debb1a8c9
Revises: 1dfc6c534742
Create Date: 2022-05-09 20:09:22.459665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284debb1a8c9'
down_revision = '1dfc6c534742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
