"""role

Revision ID: 367ad28b91a7
Revises: bc66ff23e32e
Create Date: 2022-05-27 13:44:42.456029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367ad28b91a7'
down_revision = 'bc66ff23e32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
