"""subjects

Revision ID: 3de498031ca2
Revises: e0b9d60ce904
Create Date: 2022-05-08 21:18:31.559305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de498031ca2'
down_revision = 'e0b9d60ce904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
