"""subjects

Revision ID: 420c0a9dde40
Revises: 776aaee6d1ea
Create Date: 2022-05-08 23:06:22.724772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420c0a9dde40'
down_revision = '776aaee6d1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
