"""subs

Revision ID: 4f4d1fae0dab
Revises: f0fbb6f1ed7d
Create Date: 2022-05-22 01:59:32.230638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4d1fae0dab'
down_revision = 'f0fbb6f1ed7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
