"""role

Revision ID: 5a032ed8c48b
Revises: 4f4d1fae0dab
Create Date: 2022-05-27 13:18:21.416715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a032ed8c48b'
down_revision = '4f4d1fae0dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
