"""role

Revision ID: bc66ff23e32e
Revises: 5a032ed8c48b
Create Date: 2022-05-27 13:25:28.783339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc66ff23e32e'
down_revision = '5a032ed8c48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
